version: '3.7'

services:
   jenkins:
     image: jenkins/jenkins:lts
     privileged: true
     user: root
     ports:
      - 8081:8080
      - 50000:50000
     container_name: jenkins
     volumes:
      - ./jenkins_data:/var/jenkins_home
     networks:
       jenkins-net:

   agent:
     image: jenkins/ssh-agent:jdk11
     container_name: jenkins_agent
     privileged: true
     user: root
     container_name: agent
     expose:
       - 22
     networks:
       jenkins-net:
     environment:
       - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2......


networks:
  jenkins-net:
